name: Dynamic Runner

on: workflow_dispatch

env:
  APP_TYPE: java   # change to 'dotnet'

jobs:
  build-java:
    if: env.APP_TYPE == 'java'
    runs-on: ubuntu-latest
    steps:
      - name: Show runner
        run: echo "Running on $RUNNER_OS"

  build-dotnet:
    if: env.APP_TYPE != 'java'
    runs-on: windows-latest
    steps:
      - name: Show runner
        run: echo "Running on $RUNNER_OS"