name: Dynamic Runner

on: workflow_dispatch

env:
  APP_TYPE: java   # change to 'dotnet'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.determine-runner.outputs.runner }}
    steps:
      - id: determine-runner
        run: |
          if [ "${{ env.APP_TYPE }}" = "java" ]; then
            echo "runner=ubuntu-latest" >> $GITHUB_OUTPUT
          else
            echo "runner=windows-latest" >> $GITHUB_OUTPUT
          fi

  build:
    needs: setup
    runs-on: ${{ needs.setup.outputs.runner }}
    steps:
      - name: Show runner
        run: echo "Running  on $RUNNER_OS"